Repository OSTA-group/osta-marketplace, pull requests merged in 2024-05, with the labels that each got.

#3 Remove extensions on update
  BackEnd/src/main/java/com/osta/marketplace/shedule/ExtensionsSynchronizerSchedule.java
Labels: bug

#4 Pipelines for testing code during pull requests
  .github/workflows/pull-requests.yml
  BackEnd/gradlew
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/test/tests.test.ts
  FrontEnd/vite.config.ts
Labels: enhancement

#7 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#9 Change contribute link to main page OSTA Github
  FrontEnd/src/pages/HomeScreen.tsx
Labels: enhancement

#11 Add new privacy screen, link in footer and routing
  FrontEnd/src/App.tsx
  FrontEnd/src/components/Footer.tsx
  FrontEnd/src/pages/PrivacyScreen.tsx
Labels: documentation

#15 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#16 14 add testing to markerplace backend
  BackEnd/src/main/java/com/osta/marketplace/config/AppConfig.java
  BackEnd/src/main/java/com/osta/marketplace/controller/ExtensionController.java
  BackEnd/src/main/java/com/osta/marketplace/exception/NoVersionException.java
  BackEnd/src/main/java/com/osta/marketplace/exception/ResourceNotFoundException.java
  BackEnd/src/main/java/com/osta/marketplace/repository/ExtensionRepository.java
  BackEnd/src/main/java/com/osta/marketplace/shedule/ExtensionsSynchronizerSchedule.java
  BackEnd/src/test/java/com/osta/marketplace/controller/ExtensionControllerTest.java
  BackEnd/src/test/resources/application.yml
  BackEnd/src/test/resources/data.sql
Labels: enhancement
