Repository OSTA-group/osta-marketplace, pull requests merged in 2024-06, with the labels that each got.

#18 Fix overflow on detail screen of extension
  FrontEnd/src/components/css/style.css
  FrontEnd/src/pages/Extensions/ExtensionDetailScreen.tsx
Labels: bug

#22 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#21 Update LICENSE
  LICENSE
Labels: documentation

#23 Testing the schedule download json file
  BackEnd/build.gradle.kts
  BackEnd/src/main/java/com/osta/marketplace/config/AppConfig.java
  BackEnd/src/main/java/com/osta/marketplace/schedule/ExtensionsSynchronizerSchedule.java
  BackEnd/src/main/java/com/osta/marketplace/schedule/dto/ExtensionDto.java
  BackEnd/src/main/java/com/osta/marketplace/schedule/dto/ExtensionVersionDto.java
  BackEnd/src/test/java/com/osta/marketplace/schedule/ExtensionsSynchronizerScheduleTest.java
  BackEnd/src/test/resources/application.yml
Labels: enhancement

#25 Add link to playstore
  FrontEnd/src/pages/HomeScreen.tsx
Labels: enhancement, good first issue

#29 Updated vulnerable packages
  FrontEnd/package-lock.json
Labels: bug
